### ISSUE TITLE
nach flashen - komischer Text und JSON error ?

### ISSUE THREAD

**Issue by Seqway** [jp112sdl/MatrixDisplayESP8266#16]
Hallo Jerome,
soweit konnte ich nun alles anschliessen und flashen und das war auch erfolgreich.
Eine Laufschrift habe ich auch aber da kann ich nichts von lesen! keine Ahnung was da steht.

Nach dem flashen im seriellen Monitor stand dies hier - kannst du damit was anfangen und die "7" wird immer mehr ? Ausserdem steht da ja ein JSON error. Was tun

77777777777777777777loadSystemConfig JSON DeserializationError
Failed to load config
SSID = Dirk@Home
Connecting WLAN the classic way...
..............Wifi Connected
NTP time was set
77777777777777777777777777777777777777777777777777

**Comment by Seqway** [comment]
Ich denke die komische Anzeige liegt daran das nach dem flashen im seriellen Monitor zuerst immer diese hier kommt. Daher denke ich funktioniert das nicht oder ???

Failed to parse config file
Failed to load config

**Comment by jp112sdl** [comment]
Warst du bereits im AP-Modus und hast CCU IP etc konfiguriert?

**Comment by jp112sdl** [comment]
Nimm mal den Code aus dem [Dev-Branch](https://github.com/jp112sdl/MatrixDisplayESP8266/tree/dev).

Du brauchst ArduinoJSON 6.2.3-beta und MD Parola 3.0.1

**Comment by Seqway** [comment]
Benutze den Code aus dem DEV für MatrixDisplayESP8266.ino

ABER NICHT für ConfigFileHandling
JSON 6.2.3 ist installiert sowie Parola 3.0.1

**Comment by jp112sdl** [comment]
> ABER NICHT für ConfigFileHandling

Man verwendet Branches immer konsistent und nicht nur partiell.

**Comment by Seqway** [comment]
Dann lade ich diese jetzt auch.
aber kommen Fehler - hier nur ein Auszug:
MatrixDisplayESP8266:1: error: stray '#' in program

  und versuche es.#include <MD_Parola.h>

                  ^

MatrixDisplayESP8266:1: error: 'und' does not name a type

  und versuche es.#include <MD_Parola.h>

  ^

MatrixDisplayESP8266:17: error: 'textEffect_t' does not name a type

 textEffect_t scrollEffectIn  = PA_SCROLL_LEFT

**Comment by Seqway** [comment]
Moment ... war falsches Verzeichnis.

**Comment by Seqway** [comment]
okay kompoilieren erfolgreich.....wie soll ich jetzt mal laden ? mit Debug ?

**Comment by jp112sdl** [comment]
> wie soll ich jetzt mal laden ? mit Debug ?

Was wie wo?

Starte das Ding einfach mal, geh in den AP-Modus, gibt nochmals die CCU IP usw. ein, dann speichern. Da wird die Config neu geschrieben.

**Comment by Seqway** [comment]
Weiterhin das gleiche Probleme:

77777777777777777777loadSystemConfig JSON DeserializationError
Failed to load config
SSID = Dirk@Home
Connecting WLAN the classic way...
.Wifi Connected
NTP time was set
777777777777777777777777777777777777

**Comment by Seqway** [comment]
So, wie gesagt, beim flashen kommt Fehler wie geschrieben.

Habe nun AP Modus aktiviert und alles eingegeben und die url lautet:
http://ipiobroker:8087/getPlainValue/hm-rega.0.16842

Ich mach das über den simpleadapter. Gebe ich diesen Befehl ein dann kommt der Wert im Browser auch. Aber im Display nur kauderwelsch

**Comment by Seqway** [comment]
Hier mal ein Video

https://www.youtube.com/watch?v=A3bfrwDxdz0&feature=share

**Comment by Seqway** [comment]
Keine Ahnung weiss nicht mehr weiter

**Comment by jp112sdl** [comment]
Wie gesagt - es wäre mal noch wichtig zu sehen, was kommt, wenn die Config gespeichert wird.
Also wenn du im AP-Mode auf Speichern klickst wird `saveSysConfig()` aufgerufen und auch die JSON Daten werden dort noch mal ausgegeben.

**Comment by Seqway** [comment]
in dem seriellen Monitor erscheint gar nichts wenn ich auf SAVE gehe.

Vorher war das kompilieren fehlerhaft, da ging es gar nicht. Nun kompiliert er ohne Fehler und lädt hoch und dann kommt in der Ausgabe der Fehler wie oben gepostet.

**Comment by Seqway** [comment]
Weiss nicht genau was du meinst. Aber wenn ich auf SAVE klicke dann steht in dem gleichen Fenster folgendes - ich dachte du meintest den seriellen Monitor:

Credentials Saved
Trying to connect ESP to network.
If it fails reconnect to AP to try again

**Comment by jp112sdl** [comment]
...ja ich meine im seriellen Monitor.

Wenn da schon nichts kommt, wenn du auf Save klickst, dann liegt da schon der Fehler - die Configdaten werden gar nicht abgespeichert, deshalb können sie auch anschließend nicht geladen werden.
Scheint irgendwas mit dem WiFiManager nicht zu klappen.
Kannst ja von dem mal eine ältere Version testen.

**Comment by Seqway** [comment]
Okay, da habe ich noch keine andere Version benutzt. Ich nehme mal die 0.12

**Comment by Seqway** [comment]
Nein geht leider nicht. Bei Version 0.12 und 0.13 kommt jeweils immer dieser Fehler - ich muss also 0.14 benutzen.

Archiving built core (caching) in: C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_cache_891493\core\core_esp8266_esp8266_d1_mini_CpuFrequency_80,VTable_flash,FlashSize_4M1M,LwIPVariant_v2mss536,Debug_Disabled,DebugLevel_None____,FlashErase_none,UploadSpeed_115200_2bd810b706949fdb53083a9b2af1b257.a
Linking everything together...
"C:\Users\Entwicklung\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-gcc" -CC -E -P -DVTABLES_IN_FLASH "C:\Users\Entwicklung\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.2/tools/sdk/ld/eagle.app.v6.common.ld.h" -o "C:\Users\Entwicklung\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.2/tools/sdk/ld/eagle.app.v6.common.ld"
"C:\Users\Entwicklung\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-gcc" -Wl,-Map "-Wl,C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995/MatrixDisplayESP8266.ino.map" -g -w -Os -nostdlib -Wl,--no-check-sections -u app_entry -u _printf_float -u _scanf_float -Wl,-static "-LC:\Users\Entwicklung\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.2/tools/sdk/lib" "-LC:\Users\Entwicklung\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.2/tools/sdk/ld" "-LC:\Users\Entwicklung\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.2/tools/sdk/libc/xtensa-lx106-elf/lib" "-Teagle.flash.4m1m.ld" -Wl,--gc-sections -Wl,-wrap,system_restart_local -Wl,-wrap,spi_flash_read  -o "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995/MatrixDisplayESP8266.ino.elf" -Wl,--start-group "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\sketch\MatrixDisplayESP8266.ino.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_PZone.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola_Blinds.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola_Close.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola_Diag.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola_Dissolve.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola_Fade.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola_Grow.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola_HScroll.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola_Mesh.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola_Open.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola_Print.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola_Random.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola_Scan.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola_Slice.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola_Sprite.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola_VScroll.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_Parola\MD_Parola_Wipe.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_MAX72XX\MD_MAX72xx.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_MAX72XX\MD_MAX72xx_buf.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_MAX72XX\MD_MAX72xx_font.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\MD_MAX72XX\MD_MAX72xx_pix.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\Time-master\DateStrings.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\Time-master\Time.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WiFi\BearSSLHelpers.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WiFi\CertStoreBearSSL.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WiFi\ESP8266WiFi.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WiFi\ESP8266WiFiAP.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WiFi\ESP8266WiFiGeneric.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WiFi\ESP8266WiFiMulti.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WiFi\ESP8266WiFiSTA.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WiFi\ESP8266WiFiScan.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WiFi\WiFiClient.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WiFi\WiFiClientSecureAxTLS.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WiFi\WiFiClientSecureBearSSL.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WiFi\WiFiServer.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WiFi\WiFiServerSecureAxTLS.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WiFi\WiFiServerSecureBearSSL.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WiFi\WiFiUdp.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266HTTPClient\ESP8266HTTPClient.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\WiFiManager\WiFiManager.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WebServer\ESP8266WebServer.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WebServer\ESP8266WebServerSecureAxTLS.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WebServer\ESP8266WebServerSecureBearSSL.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WebServer\Parsing.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266WebServer\detail\mimetable.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\DNSServer\DNSServer.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ArduinoOTA\ArduinoOTA.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\SPI\SPI.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\ESP8266mDNS\ESP8266mDNS.cpp.o" "C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995/arduino.ar" -lhal -lphy -lpp -lnet80211 -llwip2 -lwpa -lcrypto -lmain -lwps -lbearssl -laxtls -lespnow -lsmartconfig -lairkiss -lwpa2 -lstdc++ -lm -lc -lgcc -Wl,--end-group  "-LC:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995"
C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\WiFiManager\WiFiManager.cpp.o: In function `WiFiManager::waitForConnectResult()':

C:\Users\Entwicklung\Documents\Arduino\libraries\WiFiManager/WiFiManager.cpp:759: undefined reference to `WPS_is_unavailable_in_this_configuration__Please_check_FAQ_or_board_generator_tool'

C:\Users\ENTWIC~1\AppData\Local\Temp\arduino_build_14995\libraries\WiFiManager\WiFiManager.cpp.o: In function `WiFiManager::startWPS()':

C:\Users\Entwicklung\Documents\Arduino\libraries\WiFiManager/WiFiManager.cpp:759: undefined reference to `WPS_is_unavailable_in_this_configuration__Please_check_FAQ_or_board_generator_tool'

collect2.exe: error: ld returned 1 exit status

Mehrere Bibliotheken wurden für "WiFiUdp.h" gefunden
 Benutzt: C:\Users\Entwicklung\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi
 Nicht benutzt: D:\Daten\arduino-1.8.5\libraries\WiFi
 Nicht benutzt: D:\Daten\arduino-1.8.5\libraries\WiFi
 Nicht benutzt: D:\Daten\arduino-1.8.5\libraries\WiFi
 Nicht benutzt: D:\Daten\arduino-1.8.5\libraries\WiFi

**Comment by Seqway** [comment]
keine Ahnung.....bin ratlos

**Comment by jp112sdl** [comment]
https://github.com/tzapu/WiFiManager/issues/650

Nimm mal ESP8266 Core V. 2.4.1 oder 2.4.0
und WiFiManager 0.12

**Comment by Seqway** [comment]
Was meinst du mit --> ESP8266 Core V. 2.4.1 oder 2.4.0 ? Board Manager ? wie heisst dann da die Bibliothek ?

**Comment by jp112sdl** [comment]
Ja. Board Manager. Da kannst du sicher zwischen mehreren Versionen wählen.
Was meinst du mit Bibliothek?

**Comment by Seqway** [comment]
Okay, unter Boardmanager nicht unter Sketch

**Comment by Seqway** [comment]
Ne da kommt nix im seriellen Monitor :-(

**Comment by jp112sdl** [comment]
Dann bin ich auch grad überfragt. 
Eigentlich ging’s bisher immer. 
Hab auch erst in ein paar Wochen die Hardware wieder zum Testen zur Verfügung.

**Comment by Seqway** [comment]
der ESP hängt an meinem Laptop per USB. Wenn ich aber die Wifi AP konfiguriere, mache ich das über mein Handy, da das da besser geht. Windows Wlan will nicht immer. Ist das schlimm ? Kommt deswegen nix am seriellen Monitor ?

**Comment by Seqway** [comment]
Welches Board muss man auswählen ??? Ich habe --> Wemos D1R2 & mini

**Comment by jp112sdl** [comment]
Ja das ist richtig

**Comment by Seqway** [comment]
Ne sorry. es geht nicht. der ESP startet zwar neu, das sehe weil die Hyroglyphen Laufschrift auf einmal kommt aber in der COM6 seriellen Monitor ist nix. Keine Meldungen.
Ich weiss nicht mehr weiter und lege das nun inne Ecke :-(

**Comment by jp112sdl** [comment]
Ich habe das Problem eingrenzen können. Bin dran...

**Comment by jp112sdl** [comment]
Meine Recherchen haben ergeben: 

 - die Debugausgabe `7` kommt/kam von einer überflüssigen Debugausgabe in der MD_MAX72XX Lib. Das ist mittlerweile [gefixt](https://github.com/MajicDesigns/MD_MAX72XX/commit/155c5c594a97b69d66c65d6e4a4c2b07c0dca0cd), jedoch noch nicht über den Bibliotheksmanager aktualisierbar.
Also entweder ignorieren, oder ZIP ausm Github benutzen oder Zeile selbst auskommentieren.

 - Mit dem aktuellen WiFiManager wird keine WLAN Verbindung aufgebaut, wenn man sie speichern will. Der Verbindungstest schlägt fehl; daher wird auch die JSON nicht gespeichert.
Ich habe nun mein eigenes Derivat des WifiManager mit eingebaut, so dass man unabhängig von der Lib ist.

 - Mein Display wird korrekt angezeigt wenn ich Hardware `FC16_HW` nutze. Ist aber jetzt auch so schon im Code drin, wie er im dev-Branch hochgeladen ist.

-> Nimm noch mal den kompletten [dev-Branch](
https://github.com/jp112sdl/MatrixDisplayESP8266/archive/dev.zip) und versuch es damit mal.

ESP8266 Board Version 2.4.2
ArduinoJSON 6.2.3-beta (oder 6.3.0-beta geht auch)

**Comment by Seqway** [comment]
Hallöchen,
mit der Hilfe eines Kollegen habe ich es mit der ursprünglichen Version hinbekommen.
Es war im Prinzip tatsächlich das falsche Display. Man musste das FC16 einstellen, dass zeigt er es richtig an.

Jetzt läuft es mit der 6.2.3 und Board 2.4.1 allerdings nicht mit deinen neuen ino-Dateien, das habe ich jetzt nicht mehr getestet.

**Comment by Seqway** [comment]
Nach ein paar mal durchlaufen wird mir nur noch die Zeit eingeblendet aber nicht mehr der Datenpunkt :-( beschäftige ich mich morgen mit. Ist wohl schon zu spät für mich :-)

**Comment by jp112sdl** [comment]
Ja, nimmst vielleicht doch mal die neue Dev.
FC16 ist schon im Code eingestellt.

**Comment by Seqway** [comment]
Ja habe ich genommen. Damit geht es auch nun. Nur ein paar Texte in der Wlan-Config-Oberfläche sind verrutscht. Geht aber. Und der ESP startete nicht - musste ihn einmal vom Strom abnehmen.

Abschließend eine Frage:
Momentan schreibe ich alles in eine Variable! Somit geht die Laufschrift los und arbeitet in einem durch alle Datenpunkte. Kann man das auch so machen, dass immer nur ein Datenpunkt angezeigt wird und dann quasi weitergeblättert wird ?

**Comment by jp112sdl** [comment]
Nein... bzw. ich werde an dem Code nichts verändern.
Machen kann man alles...

Es ist so gedacht, dass aus einer einzelnen Zeichenkette, die durch Trennzeichen getrennt ist, die einzelnen Anzeigeelemente nacheinander durchgescrollt werden.

**Comment by Seqway** [comment]
Okay ! Nun läuft es ja :-) war ja nur eine Frage

**Comment by jp112sdl** [comment]
Alles bestens! 👍
