### ISSUE TITLE
Minimalistische Lösung

### ISSUE THREAD

**Issue by Tutus-B** [jp112sdl/MatrixDisplayESP8266#19]
Mit herzlichem Dank an alle, die die Vorarbeiten geleistet und hier veröffentlicht haben, stelle ich meine minimalistische Lösung vor. Die vier Module kommen von TOOGOO, die Teile links und rechts sind auf dem 3D-Drucker entstanden. Ein vollständiges Gehäuse spare ich mir, weil das Teil 2,4 m hoch steht. Im Sketch habe ich kleine Änderungen vorgenommen, um den Wochentag und Sekunden sehen zu können. Die Wetterdaten kommen von der CCU2. Für die Stromversorgung nutze ich ein älteres Netzteil, das ca. 4,6 V liefert. ESP und Matrix sind getrennt angeschlossen.
![dsc09143_](https://user-images.githubusercontent.com/46022122/50280609-40f06500-044d-11e9-822c-08ddf745858c.jpg)
![dsc09140_](https://user-images.githubusercontent.com/46022122/50280624-4b126380-044d-11e9-98ce-44fde75df162.jpg)
https://youtu.be/btK13v_Db8Q

**Comment by jp112sdl** [comment]
Ist doch gut gelungen! Top 👍
