### ISSUE TITLE
Display Aus  per http oder Cuxd 

### ISSUE THREAD

**Issue by guybrushix** [jp112sdl/MatrixDisplayESP8266#2]
Hallo, 
gibt es eine Möglichkeit das Display Ganz dunkel oder aus zu stellen wenn es nicht benötigt wird ? per cuxd Schalter oder http Befehl ? 

Gruß

**Comment by jp112sdl** [comment]
Hallo,
nein, ist nicht vorgesehen.
Du könntest dir den Quellcode höchstens so anpassen, dass die Uhrzeit nicht standardmäßig mit angezeigt wird und dann, wenn nichts angezeigt werden soll, einen leeren Text bereitstellen.

**Comment by guybrushix** [comment]
Danke für die schnelle Antwort das werde ich dann wohl so machen
