### ISSUE TITLE
keine daten abgeholt

### ISSUE THREAD

**Issue by liv-in-sky** [jp112sdl/MatrixDisplayESP8266#21]
hallo, ich denke, alte projekte zu supporten nervt wahrscheinlich - aber ich würde deine hilfe brauchen. ich habe den d1 mini geflasht bekommen und kann ihn mit web einrichten. die schalter machen auch, was sie sollen - leider wird mein iobroker text nicht abgeholt bzw. nicht angezeigt - ping funktioniert - also im netz angemeldet.
wenn ich im iobroker den simple-api deaktiviere hat das auch keine änderung zu folge - irgendwie startet das das http get nicht? 
meine url sieht so aus: http://192.168.178.59:8087/getPlainValue/controll-own.0.Matrix sieht so aus
mit tasker oder browser kann ich den wert auslesen?
hast du irgendeine idee dazu?

**Comment by jp112sdl** [comment]
Hi,

>  irgendwie startet das das http get nicht?

Am besten mal schauen, was seriell ausgegeben wird (115200 baud).

> mit tasker oder browser kann ich den wert auslesen?

Wie sieht denn die Ausgabe konkret aus?

**Comment by liv-in-sky** [comment]
hi - estmal danke für deine antwort

momentan habe ich eine uhr - entweder stillstehnede uhrzeit oder links kommend und nach oben verschwindend - mit taster geschaltet

das mit dem seriellen monitor check ich nicht ganz - wenn ich den aufrufe (com8 bei mir), kann ich nichts sehen - der monitor geht auf, das war es - muss ich da noch was machen?
 - im browser ist die ausgabe je nach dem, was ich im iobroker-text-feld" eingebe: bei test ist im browser "test" zu sehen bei "test" im iobroker kommt  "\"test\"" heraus.

ich habe mal anstatt der uhrzeit etwas anderes ausgeben lassen - funktioniert auch - habe die .ino datei geändert um zu sehen, ob die flases auch richtig ankommmen.

**Comment by liv-in-sky** [comment]
neuigkeiten beim seriellen monitor - beim schalten mit D2 kommt folgendes - sonst passiert nichts
![image 1](https://user-images.githubusercontent.com/18462890/51038863-7a337500-15b4-11e9-99d7-a77ed79324a6.png)

**Comment by liv-in-sky** [comment]
I'm sorry - habe fehler gefunden - ich hatte wohl den falschen wemos konfiguriert - hatte esp version 2.5 beta2  - der boardtreiber hat einen anderen wemos d1 mini dabei .

werd mich mal im ändern versuchen - hätte gerne eine stehende uhr, wenn http get leer 

und abends würd ich gerne das display ausschalten können - hab sowas noch nie gemacht - werd wohl bis zum frühling dafür brauchen

tolles project - danke für's teilen
