### ISSUE TITLE
Einbindung Iobroker

### ISSUE THREAD

**Issue by mikewolf** [jp112sdl/MatrixDisplayESP8266#3]
Hallo , gibt es  irgendwo ne Anleitung wie ich das Display via Iobroker per Mqtt beschreiben kann ?
kann leider nichts finden und die CCU möchte ich eigentlich nicht befeuern , diese soll sich nur um Wichtige Dinge kümmern ,alles andere nice to have via Iobroker .

Mit freundlichen Grüßen
mikewolf

wäre sicher den einen oder andern auch Interessieren

**Comment by mikewolf** [comment]
Super, Danke werde ich heute noch probieren,
eine Frage hätte ich noch 👍 
kann man nachträglich noch die Einstellungen ändern ,oder geht die Änderung nur bei Ersteinrichtung,
habe diesbezüglich nichts im Sketch gefunden ?
mfg
mikewolf

**Comment by jp112sdl** [comment]
Änderung geht nur via Ersteinrichtung.
So oft ändert man da ja auch nix ;)

**Comment by mikewolf** [comment]
perfekt Danke !
