### ISSUE TITLE
Neustart des Wemos bei zu langen Text

### ISSUE THREAD

**Issue by 1hotte** [jp112sdl/MatrixDisplayESP8266#6]
Hallo der Wemos stürzt ab und startet neu bei zu langen Text. Hat das einen Grund das du ihn auf 75 Zeichen begrenzt hast  ?

**Comment by jp112sdl** [comment]
Hallo.
Nein, mir fällt zumindest kein Grund ein.

Wenn du mehr Zeichen brauchst, dann erhöhe den Wert.

**Comment by 1hotte** [comment]
ok . Ich dachte da gäbe es einen Hintergrund zu.
