### ISSUE TITLE
Variable Animation

### ISSUE THREAD

**Issue by 1hotte** [jp112sdl/MatrixDisplayESP8266#7]
Ist es möglich die Animation art als Vari. mit zu schicken?

**Comment by jp112sdl** [comment]
Möglich ist alles :)

Das Projekt ist "wie es ist". 
Jeder kann den Quelltext nutzen und nach belieben ändern.

Als Idee:
Da es keinen Webservice gibt, sondern die Werte nur gepullt werden, könntest du evtl. über reservierte Wörter mit Trennzeichen noch Steuerinformationen mitgeben und diese anschließend aus dem empfangenen String herausfiltern.

**Comment by 1hotte** [comment]
OK, Ich werde es mal versuchen . Ich bin da nicht so bewandert mit , aber Danke für den Tip .
Ach ja Tolles Projekt.
